<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CharacterSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $rows = [
            ['game_id' => 1, 'name' => '博麗 靈夢', 'title' => '樂園的巫女', 'description' => '博麗神社的巫女。平時會在境內掃地，或是悠閒地等待參拜客。每當異變發生時便會隻身前往解決，是幻想鄉的守護者。擁有飛行與靈力，專職退治妖怪。', 'ability' => '具有空中飛行程度的能力', 'theme_music' => '少女綺想曲 ～ Dream Battle', 'spell_card' => '夢符「封魔陣」', 'color' => '#8B0000', 'accent_color' => '#FFB7C5', 'image_path' => 'assets/img/chars/reimu.webp', 'artist' => '毛毛工坊-凉貓', 'created_at' => now(), 'updated_at' => now()],
            ['game_id' => 1, 'name' => '霧雨 魔理沙', 'title' => '普通的魔法使', 'description' => '居住在魔法之森的魔法使。憑藉自學精通魔法的努力型天才。擅長威力強大、充滿爆發力的光熱魔法，好奇心旺盛。與愛麗絲是朋友關係。', 'ability' => '具有使用魔法程度的能力', 'theme_music' => '戀色Master Spark', 'spell_card' => '戀符「極限火花」', 'color' => '#4A3800', 'accent_color' => '#FFD700', 'image_path' => 'assets/img/chars/marisa.webp', 'artist' => '毛毛工坊-凉貓', 'created_at' => now(), 'updated_at' => now()],
            ['game_id' => 1, 'name' => '十六夜 咲夜', 'title' => '完美且瀟灑的女僕', 'description' => '在紅魔館工作的瀟灑女僕長。擁有使時間靜止的能力，能自在地操縱飛刀。誓死效忠蕾米莉亞，凡事以她的安全為最優先的完美主義者。', 'ability' => '具有操縱時間程度的能力', 'theme_music' => '月時計 ～ Lunatic Dial', 'spell_card' => '時符「完美空間」', 'color' => '#1A1A4E', 'accent_color' => '#C0C8E0', 'image_path' => 'assets/img/chars/sakuya.webp', 'artist' => '毛毛工坊-凉貓', 'created_at' => now(), 'updated_at' => now()],
            ['game_id' => 1, 'name' => '蕾米莉亞·斯卡蕾特', 'title' => '紅之惡魔', 'description' => '紅魔館的主人，活了500年的吸血鬼領主。擁有操縱命運的能力，是芙蘭朵露的姐姐。雖然外表年幼，卻擁有壓倒性的高傲威嚴，是幻想鄉中屈指可數的大妖怪。', 'ability' => '具有操縱命運程度的能力', 'theme_music' => '亡き王女の為のセプテット', 'spell_card' => '紅符「緋紅射擊」', 'color' => '#4A0A20', 'accent_color' => '#FF4466', 'image_path' => 'assets/img/chars/remilia.webp', 'artist' => '毛毛工坊-凉貓', 'created_at' => now(), 'updated_at' => now()],
            ['game_id' => 1, 'name' => '芙蘭朵露·斯卡蕾特', 'title' => '惡魔的妹妹', 'description' => '蕾米莉亞的妹妹。曾被禁錮在地下室長達495年。擁有將一切眼前所見之物徹底破壞的異能，精神層面較不穩定。與可愛的外表相反，內心深藏著恐怖的力量。', 'ability' => '具有將一切不論何種事物盡皆破壞程度的能力', 'theme_music' => 'U.N.オーエンは彼女なのか？', 'spell_card' => '禁忌「禁忌之果」', 'color' => '#3A0A50', 'accent_color' => '#FF6B00', 'image_path' => 'assets/img/chars/flandre.webp', 'artist' => '毛毛工坊-凉貓', 'created_at' => now(), 'updated_at' => now()],
            ['game_id' => 2, 'name' => '八雲 紫', 'title' => '幻想的境界', 'description' => '幻想鄉的管理者之一，操縱境界的大妖怪。將八雲藍作為式神使役。作為「大賢者」肩負著維持幻想鄉均衡的重任。平時過著隱居生活，白天基本都在睡覺。', 'ability' => '具有操縱境界程度的能力', 'theme_music' => 'ネクロファンタジア', 'spell_card' => '境符「四重結界」', 'color' => '#2A1040', 'accent_color' => '#CC88FF', 'image_path' => 'assets/img/chars/yukari.webp', 'artist' => '毛毛工坊-凉貓', 'created_at' => now(), 'updated_at' => now()],
            ['game_id' => 2, 'name' => '魂魄 妖夢', 'title' => '半人半靈的庭師', 'description' => '白玉樓的庭師兼專屬劍士。身為人與幽靈的混血半妖。一邊盡心侍奉幽幽子，一邊不懈地修行武術。雖然是精通雙刀流的劍術達人，但在幽幽子面前完全抬不起頭。', 'ability' => '具有使用劍術的能力', 'theme_music' => '広有射怪鳥事 ～ Till When?', 'spell_card' => '人符「現世斬」', 'color' => '#0A3020', 'accent_color' => '#88FFCC', 'image_path' => 'assets/img/chars/youmu.webp', 'artist' => '毛毛工坊-凉貓', 'created_at' => now(), 'updated_at' => now()],
            ['game_id' => 2, 'name' => '西行寺 幽幽子', 'title' => '冥界的蝶', 'description' => '白玉樓的主人。過去曾是人類，死後化為亡靈。雖然擁有操縱死亡程度的恐怖能力，但其性格卻十分天然呆且悠哉，食欲極其旺盛。', 'ability' => '具有操縱死亡程度的能力', 'theme_music' => '幽雅に咲かせ、墨染の桜 ～ Border of Life', 'spell_card' => '死符「驚懼幻夢」', 'color' => '#1A0A30', 'accent_color' => '#FF88CC', 'image_path' => 'assets/img/chars/yuyuko.webp', 'artist' => '毛毛工坊-凉貓', 'created_at' => now(), 'updated_at' => now()],
            ['game_id' => 1, 'name' => '琪露諾', 'title' => '最強的冰之妖精', 'description' => '居住在霧之湖的冰之妖精。自稱「最強的妖精」。以笨蛋性格聞名，常被粉絲冠上「⑨」的代號。擁有操縱冷氣的能力，平時熱衷於把青蛙冰凍起來。', 'ability' => '具有操縱冷氣程度的能力', 'theme_music' => 'おてんば恋娘', 'spell_card' => '冰符「冰瀑」', 'color' => '#0A2A4A', 'accent_color' => '#88DDFF', 'image_path' => 'assets/img/chars/cirno.webp', 'artist' => '毛毛工坊-凉貓', 'created_at' => now(), 'updated_at' => now()],
            ['game_id' => 1, 'name' => '紅 美鈴', 'title' => '紅魔館的門番', 'description' => '紅魔館的看門人。來自中國的妖怪，同時也是氣功與武術的大師。然而因為看門時偷懶打瞌睡而聞名，雖然屢次被咲夜教訓，依然非常有精神地履行職責。', 'ability' => '具有操縱氣程度的能力', 'theme_music' => '明治十七年の上海アリス', 'spell_card' => '彩符「彩光風鈴」', 'color' => '#3A1A00', 'accent_color' => '#FF8844', 'image_path' => 'assets/img/chars/meiling.webp', 'artist' => '毛毛工坊-凉貓', 'created_at' => now(), 'updated_at' => now()],
            ['game_id' => 1, 'name' => '帕秋莉·諾蕾姬', 'title' => '一星期魔法使', 'description' => '隱居在紅魔館大圖書館的魔女。持續進行了100年以上的魔法研究。患有哮喘导致體質虛弱，長年閉門不出。非常討厭魔理沙來圖書館「借」走她的珍貴書籍。', 'ability' => '具有操縱火水木金土日月（七曜）魔法程度的能力', 'theme_music' => 'ラクトガール ～少女密室', 'spell_card' => '火金符「聖艾爾摩之柱」', 'color' => '#1A1040', 'accent_color' => '#CC88CC', 'image_path' => 'assets/img/chars/patchouli.webp', 'artist' => '毛毛工坊-凉貓', 'created_at' => now(), 'updated_at' => now()],
            ['game_id' => 4, 'name' => '藤原 妹紅', 'title' => '拒絕死亡的蓬萊不死人', 'description' => '因服用了蓬萊之藥而獲得不死之身的人類。與輝夜展開了長達千年以上的宿命死鬥。平時生活在人類村落附近，偶爾會主動現身引導並解救迷失在竹林中的人類。', 'ability' => '具有不老不死與操縱火焰程度的能力', 'theme_music' => '月まで届け、不死の煙', 'spell_card' => '不死「凱風快晴飛翔腳」', 'color' => '#3A0A00', 'accent_color' => '#FF4400', 'image_path' => 'assets/img/chars/mokou.webp', 'artist' => '毛毛工坊-凉貓', 'created_at' => now(), 'updated_at' => now()],
            ['game_id' => 2, 'name' => '愛麗絲·瑪格特羅伊德', 'title' => '七彩的魔法使', 'description' => '居住在魔法之森的人形使。擁有高超的人偶操縱技術，能同時讓複數人偶做出如同具備自我意識般精細的動作。與魔理沙是鄰居，性格看似冷淡其實相當照顧人。', 'ability' => '具有操縱人偶程度的能力', 'theme_music' => '人形裁判 ～ 人形を操作する程度の能力', 'spell_card' => '魔符「阿提米絲」', 'color' => '#0044AA', 'accent_color' => '#FFDD55', 'image_path' => 'assets/img/chars/alice.webp', 'artist' => '毛毛工坊-凉貓', 'created_at' => now(), 'updated_at' => now()],
            ['game_id' => 4, 'name' => '鈴仙·優曇華院·因幡', 'title' => '狂氣的月兔', 'description' => '從月球逃亡到永遠亭的月兔。雙眼擁有讓人陷入瘋狂與幻覺的波動力量。平時在永遠亭幫忙因幡帝管理兔群，也常到人類村落販售輝夜特製的蓬萊藥。', 'ability' => '具有操縱波長（狂氣）程度的能力', 'theme_music' => '狂気の瞳 ～ Invisible Full Moon', 'spell_card' => '散符「真實之月」', 'color' => '#4B0082', 'accent_color' => '#FFBBFF', 'image_path' => 'assets/img/chars/reisen.webp', 'artist' => '毛毛工坊-凉貓', 'created_at' => now(), 'updated_at' => now()],
            ['game_id' => 8, 'name' => '比那名居 天子', 'title' => '非想非非想天之娘', 'description' => '居住在天界的傲慢天人大小姐。因為天界生活太過無聊而多次引發異變。手持能夠操縱大地的要石與能看穿氣質的緋想之劍，性格任性、極度渴望樂趣。', 'ability' => '具有操縱大地程度的能力', 'theme_music' => '有頂天変 ～ Wonderful Heaven', 'spell_card' => '要石「天地開闢」', 'color' => '#003366', 'accent_color' => '#88CCFF', 'image_path' => 'assets/img/chars/tenshi.webp', 'artist' => '毛毛工坊-凉貓', 'created_at' => now(), 'updated_at' => now()],
            ['game_id' => 9, 'name' => '古明地 戀', 'title' => '閉塞的戀之瞳', 'description' => '古明地覺的妹妹。因為不希望像姐姐一樣讀取到他人的險惡內心，而主動閉上了第三隻眼。從此失去了讀心能力，但也獲得了完全在無意識中行動的特殊體質。', 'ability' => '具有操縱無意識程度的能力', 'theme_music' => 'ハルトマンの妖怪少女', 'spell_card' => '抑制「超自我」', 'color' => '#004D40', 'accent_color' => '#99FF99', 'image_path' => 'assets/img/chars/koishi.webp', 'artist' => '毛毛工坊-凉貓', 'created_at' => now(), 'updated_at' => now()],
            ['game_id' => 9, 'name' => '古明地 覺', 'title' => '怨靈亦恐懼的少女', 'description' => '地靈殿的主人，戀的姐姐。擁有讀取他人內心的強大能力，因此受到地底妖怪們的敬畏與排擠。平時與大量的寵物一同生活在地靈殿，極具威嚴與智慧。', 'ability' => '具有讀取內心（讀心術）程度的能力', 'theme_music' => '少女さとり ～ 3rd eye', 'spell_card' => '想起「恐怖催眠術」', 'color' => '#4A0E4E', 'accent_color' => '#FFB6C1', 'image_path' => 'assets/img/chars/satori.webp', 'artist' => '毛毛工坊-凉貓', 'created_at' => now(), 'updated_at' => now()],
            ['game_id' => 3, 'name' => '伊吹 萃香', 'title' => '聚集百鬼的夜行', 'description' => '現身於幻想鄉的古代大鬼。極度嗜酒，手持永遠倒不完酒的伊吹瓢。擁有能操縱疏密、將身體巨大化、或是化為霧氣消散的能力。性格豪爽，與靈夢關係極佳。', 'ability' => '具有操縱疏密程度的能力', 'theme_music' => '御伽の国の鬼が島 ～ Missing Power、砕月', 'spell_card' => '鬼神', 'color' => '#3E2723', 'accent_color' => '#FFCC80', 'image_path' => 'assets/img/chars/suika.webp', 'artist' => '毛毛工坊-凉貓', 'created_at' => now(), 'updated_at' => now()],
            ['game_id' => 7, 'name' => '洩矢 諏訪子', 'title' => '土著神的頂點', 'description' => '守矢神社真正供奉的土著神、青蛙之神。雖然在過去的神話大戰中敗給了神奈子，但兩人現在共同管理守矢神社。外表像個活潑的小女孩，其實擁有深不可測的遠古神力。', 'ability' => '具有創造坤（地）程度的能力', 'theme_music' => 'ネイティブフェイス', 'spell_card' => '開宴「兩大神之譜系」', 'color' => '#5D4037', 'accent_color' => '#FFF59D', 'image_path' => 'assets/img/chars/suwako.webp', 'artist' => '毛毛工坊-凉貓', 'created_at' => now(), 'updated_at' => now()],
            ['game_id' => 15, 'name' => '秦 心', 'title' => '表情豐富的喪偶之村', 'description' => '由第六天魔王面具化身而成的面靈氣付喪神。透過更換身上配戴的 66 個面具來切換各種情感與力量。曾因弄丟「希望的面具」導致情感失控，後來在異變中找回自我。', 'ability' => '具有操縱情感程度的能力', 'theme_music' => '亡失のエモーション', 'spell_card' => '憑依「喜怒哀樂」', 'color' => '#424242', 'accent_color' => '#FF8A80', 'image_path' => 'assets/img/chars/kokoro.webp', 'artist' => '毛毛工坊-凉貓', 'created_at' => now(), 'updated_at' => now()],
            ['game_id' => 4, 'name' => '蓬萊山輝夜', 'title' => '永遠公主', 'description' => '居住在迷途竹林中永遠亭的月之公主。擁有不死之身，性格看似文靜隱蔽，實則好勝心極強。在月之都因製造蓬萊之藥而被流放地面，隨後隱居於幻想鄉。', 'ability' => '具有操縱永遠與須臾程度的能力', 'theme_music' => '竹取飛翔 ～ Lunatic Princess', 'spell_card' => '難題「蓬萊的彈枝 -七色彩虹-」', 'color' => '#4A0007', 'accent_color' => '#FFD700', 'image_path' => 'assets/img/chars/kaguya.webp', 'artist' => '毛毛工坊-涼貓', 'created_at' => now(), 'updated_at' => now()],
            ['game_id' => 7, 'name' => '東風谷早苗', 'title' => '祭祀風的人類', 'description' => '守矢神社的風祝。雖然是人類，但因為是現人神，所以能使用奇蹟的力量。隨同守矢神社的兩位神明一同從外界遷入幻想鄉，對幻想鄉的常識尚在適應中。', 'ability' => '具有引發奇蹟程度的能力', 'theme_music' => '信仰は儚き人間の為に', 'spell_card' => '秘術「灰色風暴」', 'color' => '#1E4D2B', 'accent_color' => '#A8E6CF', 'image_path' => 'assets/img/chars/sanae.webp', 'artist' => '毛毛工坊-涼貓', 'created_at' => now(), 'updated_at' => now()],
            ['game_id' => 1, 'name' => '露米婭', 'title' => '潛伏於黑暗中的妖怪', 'description' => '操控黑暗的妖怪。雖然外表像個年幼的小孩，但本質上是吃人類的妖怪。頭上綁著一條她自己無法解開的符咒絲帶，平時總是傻呼呼地張開雙臂飛在空中。', 'ability' => '具有操縱黑暗程度的能力', 'theme_music' => '妖魔夜行', 'spell_card' => '夜符「夜雀」', 'color' => '#111122', 'accent_color' => '#FF3344', 'image_path' => 'assets/img/chars/rumia.webp', 'artist' => '毛毛工坊-涼貓', 'created_at' => now(), 'updated_at' => now()],
            ['game_id' => 5, 'name' => '四季映姬·亞瑪薩那度', 'title' => '樂園的最高裁判長', 'description' => '負責審判幻想鄉死者的閻魔。由於說教極度漫長且切中要害，幻想鄉的妖怪與人類看到她都會敬而遠之。攜帶淨玻璃之鏡與悔悟之棒，公正無私地指出他人的罪過。', 'ability' => '具有是非黑白分明程度的能力', 'theme_music' => '六十年目の東方裁判　～ Fate of Sixty Years', 'spell_card' => '審判「十王之罪審」', 'color' => '#1A2A3A', 'accent_color' => '#FFB7C5', 'image_path' => 'assets/img/chars/eiki.webp', 'artist' => '毛毛工坊-涼貓', 'created_at' => now(), 'updated_at' => now()],
            ['game_id' => 7, 'name' => '犬走椛', 'title' => '下級白狼天狗', 'description' => '在妖怪之山負責千里眼警戒任務的白狼天狗。對入侵者會先進行威嚇與禮貌性勸離，如果對方不聽才會通報大天狗。私底下十分喜歡玩大天狗將棋。', 'ability' => '具有看見千里之外程度的能力', 'theme_music' => 'フォールオブフォール ～ 秋めく滝', 'spell_card' => '狗符「狂犬疾步」', 'color' => '#EEEEEE', 'accent_color' => '#8B0000', 'image_path' => 'assets/img/chars/momiji.webp', 'artist' => '毛毛工坊-涼貓', 'created_at' => now(), 'updated_at' => now()],
            ['game_id' => 19, 'name' => '純狐', 'title' => '無名的純粹憤怒', 'description' => '對月之民抱持著絕對、純粹仇恨的次代神靈。因為兒子被月之民殺害，憤怒純化成了她的存在本身。為了向嫦娥復仇，多次策劃對月之都的襲擊。', 'ability' => '具有純化程度的能力', 'theme_music' => 'Pure Furies ～ 心之所在', 'spell_card' => '「純粹的狂氣」', 'color' => '#300040', 'accent_color' => '#FF4500', 'image_path' => 'assets/img/chars/junko.webp', 'artist' => '毛毛工坊-涼貓', 'created_at' => now(), 'updated_at' => now()],
            ['game_id' => 6, 'name' => '射命丸 文', 'title' => '傳統的幻想記者', 'description' => '居住在妖怪之山上的天狗記者。經營著《文文。新聞》，每天在幻想鄉到處奔走尋找引人注目的頭條新聞。', 'ability' => '具有操縱風程度的能力', 'theme_music' => '風神少女 ～ Short Version', 'spell_card' => '突風「天狗風」', 'color' => '#404040', 'accent_color' => '#DE2A1B', 'image_path' => 'assets/img/chars/aya.webp', 'artist' => '毛毛工坊-涼貓', 'created_at' => now(), 'updated_at' => now()],
        ];

        DB::table('characters')->insert($rows);
    }
}
